<script>
	import PageNav from '$lib/docs/PageNav.svelte';
	import Callout from '$lib/docs/Callout.svelte';
	import Swatch from '$lib/design/Swatch.svelte';
	import Downloads from '$lib/design/Downloads.svelte';
	import { FLAT } from '$lib/design/nav.js';
	// generated by scripts/sync-design.sh from `ewe-theme show`, Theme.qml and
	// tokens.json — never edited by hand
	import DATA from '$lib/design/token-data.json';

	const DOWNLOADS = [
		{ href: '/design/tokens.css', label: 'tokens.css', note: 'Ewe Dark and Ewe Light as CSS custom properties' },
		{ href: '/design/tokens.json', label: 'tokens.json', note: 'The design system’s tokens, with usage notes' }
	];

	/** `code` spans in a usage note, as [text, isCode] parts */
	const parts = (s) => s.split('`').map((t, i) => [t, i % 2 === 1]);
	const COLOR = DATA.groups.find((g) => g.id === 'color');
	const OTHER = DATA.groups.filter((g) => g.id !== 'color');
	const differs = DATA.groups.flatMap((g) => g.tokens).filter((t) => t.spec);
	const weightName = { 300: 'light', 400: 'regular', 500: 'medium', 600: 'semibold' };
</script>

<svelte:head>
	<title>Token reference — Ewe design system</title>
	<meta
		name="description"
		content="Every Ewe design token: its CSS custom property, its QML Theme name, its value in Ewe Dark and Ewe Light, and what it is for — plus the type styles and the motion table."
	/>
</svelte:head>

<p class="eyebrow">Design system · documentation</p>
<h1>Token reference</h1>
<p class="lede">
	Every token the interface may use, grouped as in <code>tokens.json</code>, with its CSS and QML
	name and its value in both built-in schemes.
</p>

<Downloads items={DOWNLOADS} label="Token files" />

<section>
	<h2 id="about">Reading this page</h2>
	<p>
		The values are what <code>ewe-theme</code> emits on ewe <code>{DATA.ewe}</code> (design system
		version {DATA.version}) for Ewe Dark and Ewe Light at the defaults: the gold accent, medium
		corners, comfortable density, thin strokes and 100% text. The look presets and the accessibility
		modes remap some of them at runtime, and a person’s accent regenerates the accent ramp, so
		always ask for the token, never copy its value. The usage notes are the design system’s own.
	</p>
	<p>
		CSS custom properties are the token names. On the shell side each is a property of the
		<code>Theme</code> singleton in camelCase; radii get a <code>radius</code> prefix. This page is
		generated from the generator, <code>Theme.qml</code> and <code>tokens.json</code> by
		<code>npm run design</code>.
	</p>
	{#if differs.length}
		<Callout title="Where tokens.json and ewe differ">
			<p>
				{differs.length} tokens ship with a value other than the one <code>tokens.json</code> writes
				down, mostly colors the generator derives in OKLCH instead of copying, and
				<code>on-status</code>, which ewe keeps to its one white. The shipped value is the one in
				the table; the file’s is noted under it.
			</p>
		</Callout>
	{/if}
	<nav class="jump" aria-label="Token groups">
		{#each DATA.groups as g}<a href="#{g.id}">{g.title}</a>{/each}
		<a href="#type-styles">Type styles</a>
		<a href="#motion">Motion</a>
	</nav>
</section>

<section>
	<h2 id="color">Color <span class="count">{COLOR.tokens.length}</span></h2>
	<p class="muted">The roles every surface reads, the accent ramp and the warm neutrals.</p>

	<h3 id="live">Live on this page</h3>
	<p>
		Painted with the tokens themselves, so they show whichever scheme this site wears; switch it in
		the header.
	</p>
	<div class="live">
		{#each COLOR.tokens as t}<Swatch token={t.name} />{/each}
	</div>

	<h3 id="color-table">In both schemes</h3>
	<div class="tbl">
		<table class="tokens">
			<thead>
				<tr><th>Token</th><th>QML</th><th>Ewe Dark</th><th>Ewe Light</th><th>Usage</th></tr>
			</thead>
			<tbody>
				{#each COLOR.tokens as t}
					<tr>
						<td class="nowrap"><code>{t.css}</code></td>
						<td class="nowrap"><code>Theme.{t.qml}</code></td>
						<td class="num"><span class="chip" style="background: {t.dark}"></span>{t.dark}</td>
						<td class="num"><span class="chip" style="background: {t.light}"></span>{t.light}</td>
						<td class="usage">
							{#each parts(t.usage) as [s, c]}{#if c}<code>{s}</code>{:else}{s}{/if}{/each}
							{#if t.spec}<span class="spec">tokens.json: {t.spec}</span>{/if}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>

{#each OTHER as g}
	<section>
		<h2 id={g.id}>{g.title} <span class="count">{g.tokens.length}</span></h2>
		{#if g.note}<p class="muted">{#each parts(g.note) as [s, c]}{#if c}<code>{s}</code>{:else}{s}{/if}{/each}</p>{/if}
		<div class="tbl">
			<table class="tokens">
				<thead>
					<tr><th>Token</th><th>QML</th><th>Value</th><th>Usage</th></tr>
				</thead>
				<tbody>
					{#each g.tokens as t}
						<tr>
							<td class="nowrap"><code>{t.css}</code></td>
							<td class="nowrap"><code>Theme.{t.qml}</code></td>
							<td class="num value">
								{#if t.dark === t.light}
									{t.dark}
								{:else}
									<span class="both"><span class="lbl">Dark</span>{t.dark}</span>
									<span class="both"><span class="lbl">Light</span>{t.light}</span>
								{/if}
							</td>
							<td class="usage">
								{#each parts(t.usage) as [s, c]}{#if c}<code>{s}</code>{:else}{s}{/if}{/each}
								{#if t.extra}<span class="spec">Shipped by ewe; not in tokens.json.</span>{/if}
								{#if t.spec}<span class="spec">tokens.json: {t.spec}</span>{/if}
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</section>
{/each}

<section>
	<h2 id="type-styles">Type styles <span class="count">{DATA.styles.length}</span></h2>
	<p>
		A style is a class in CSS and an object in QML — <code>Theme.type.label.size</code>,
		<code>.lineHeight</code>, <code>.weight</code>, <code>.family</code>, <code>.italic</code> and
		<code>.letterSpacing</code>. Text size scales size and line height; nothing else changes.
	</p>
	<div class="tbl">
		<table class="styles">
			<thead>
				<tr><th>Style</th><th>CSS · QML</th><th>Size / line</th><th>Weight</th><th>Sample</th><th>Usage</th></tr>
			</thead>
			<tbody>
				{#each DATA.styles as s}
					<tr>
						<td class="nowrap"><code>{s.name}</code></td>
						<td class="nowrap"><code>{s.class}</code><br /><code>{s.qml}</code></td>
						<td class="num">{s.size} / {s.lineHeight}</td>
						<td class="nowrap">
							{weightName[s.weight] ?? s.weight}{s.italic ? ' italic' : ''}{s.family === 'mono' ? ' · mono' : ''}{s.tracking ? ` · ${s.tracking}em` : ''}
						</td>
						<td class="sample"><span class="t-{s.name}">{s.sample}</span></td>
						<td class="usage">{s.usage}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>

<section>
	<h2 id="motion">Motion</h2>
	<p>
		Motion isn’t a CSS token, so each implementation defines these once beside the tokens. The
		animation speed setting divides the durations; Reduce motion turns base and slow into fast.
	</p>
	<div class="tbl">
		<table>
			<thead>
				<tr><th>Name</th><th>Duration</th><th>CSS</th><th>QML</th><th>Curve</th><th>Used for</th></tr>
			</thead>
			<tbody>
				{#each DATA.motion as m}
					<tr>
						<td><code>{m.name}</code></td>
						<td class="num">{m.ms}ms</td>
						<td class="nowrap"><code>var({m.css})</code><br /><code>{m.cssEasing}</code></td>
						<td class="nowrap"><code>{m.qml}</code><br /><code>{m.qmlEasing}</code></td>
						<td class="nowrap">{m.easing}<br /><span class="spec">{m.curve}</span></td>
						<td>{m.usage}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>

<PageNav flat={FLAT} />

<style>
	.jump {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-xs);
		margin-top: var(--space-md);
	}
	.jump a {
		display: inline-flex;
		align-items: center;
		min-height: var(--control-md);
		padding: 0 calc(var(--space-s) + var(--space-xs));
		border: var(--border-width-1) solid var(--border-subtle);
		border-radius: var(--primary);
		background: var(--surface-raised);
		color: var(--text-primary);
		font-size: var(--font-size-md);
		text-decoration: none;
	}
	.jump a:hover {
		background: var(--surface-hover);
	}
	.count {
		font-family: var(--font-mono);
		font-size: var(--font-size-md);
		font-weight: var(--font-weight-regular);
		color: var(--text-muted);
		vertical-align: middle;
	}
	.live {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(18rem, 1fr));
		column-gap: var(--space-lg);
		margin-top: var(--space-s);
		max-width: 60rem;
	}
	.tokens {
		table-layout: fixed;
		min-width: 50rem;
	}
	.c-tok {
		width: 13rem;
	}
	.c-qml {
		width: 13rem;
	}
	.c-val {
		width: 8rem;
	}
	.c-wide {
		width: 14rem;
	}
	.tokens td {
		overflow-wrap: anywhere;
	}
	.styles {
		min-width: 60rem;
	}
	.chip {
		display: inline-block;
		width: var(--icon-sm);
		height: var(--icon-sm);
		margin-right: var(--space-xs);
		border-radius: var(--slight);
		border: var(--border-width-1) solid var(--border-subtle);
		vertical-align: middle;
	}
	.spec {
		display: block;
		margin-top: var(--space-xxs);
		font-family: var(--font-mono);
		font-size: var(--font-size-xs);
		line-height: var(--line-height-xs);
		color: var(--text-muted);
	}
	.value {
		white-space: normal;
		max-width: 20rem;
		overflow-wrap: anywhere;
	}
	.both {
		display: block;
	}
	.both + .both {
		margin-top: var(--space-xxs);
	}
	.lbl {
		color: var(--text-muted);
		margin-right: var(--space-xs);
	}
	.sample {
		color: var(--text-primary);
		white-space: nowrap;
	}
</style>
