// Regenerate src/lib/icons.js from the vendored Lucide set.
//
//   npm run icons
//
// The site draws Lucide as inline SVG rather than loading Lucide.ttf the way
// the shell and the Tauri apps do: a web page pays for a font in bytes and in
// a flash of missing glyphs, and twenty icons of path data is ~4 kB. Same
// artwork, same 24px grid, same stroke-width 2 — only the delivery differs.
//
// Add a name to NAMES, run this, commit both files. Nothing reads
// node_modules at build time, so the generated file is the only dependency
// the site actually ships.
import { readFileSync, writeFileSync } from 'node:fs';

const NAMES = [
	'arrow-right', 'bell', 'blend', 'box', 'calendar', 'cast', 'check',
	'chevron-right', 'circle-check', 'circle-user', 'cloud', 'cloud-off',
	'copy', 'download', 'external-link', 'eye', 'file-text', 'folder-sync',
	'git-branch', 'globe', 'hard-drive', 'image', 'info', 'key', 'keyboard', 'layers',
	'layout-panel-top', 'lock', 'mail', 'monitor', 'package', 'palette',
	'panel-bottom', 'refresh-cw', 'rotate-ccw', 'ruler', 'search', 'settings-2',
	'shield-check', 'shuffle', 'sliders-horizontal', 'smartphone', 'sparkles',
	'square-terminal', 'terminal', 'triangle-alert', 'type', 'usb',
	'wand-sparkles', 'wifi', 'zap'
];

const version = JSON.parse(
	readFileSync('node_modules/lucide-static/package.json', 'utf8')
).version;

const body = (name) => {
	const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, 'utf8');
	// everything between the <svg …> tag and </svg>; the attributes live on
	// the <svg> Icon.svelte writes, so only the geometry is kept here
	const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
	return inner.replace(/\s+/g, ' ').trim();
};

const out = [
	`// AUTO-GENERATED by scripts/gen-icons.mjs from lucide-static v${version} (ISC).`,
	'// Do not edit by hand — add the name to that script and re-run `npm run icons`.',
	'//',
	'// Geometry only. Every icon is drawn on Lucide\'s 24px grid at stroke-width 2,',
	'// with round caps and joins; those attributes are set once by Icon.svelte.',
	'',
	'export const ICONS = {',
	...NAMES.map((n) => `\t'${n}': '${body(n).replace(/'/g, "\\'")}',`),
	'};',
	''
].join('\n');

writeFileSync('src/lib/icons.js', out);
console.log(`ok ${NAMES.length} icons, ${(out.length / 1024).toFixed(1)} kB`);
