#!/usr/bin/env bash
# Regenerate src/tokens.css from the desktop's own token generator.
#
# There is no second source of truth: every value comes out of
# `ewe-theme build` (ewe/bin/ewe-theme, Ewe design system v3). This script
# only asks it for the two built-in schemes and stacks them so the page can
# follow the visitor's system setting and the header toggle:
#
#   :root, :root[data-theme="dark"]        Ewe Dark  (the default)
#   :root[data-theme="light"]              Ewe Light (chosen with the toggle)
#   @media (prefers-color-scheme: light)
#     :root:not([data-theme="dark"])       Ewe Light (the system asks for it)
#   [data-scheme="ewe-dark"]               Ewe Dark colour roles for one part of
#                                          the page (the hero over the photo)
#
# The generator emits Ewe token names only (the Fluent aliases are gone). Its
# closing `--accent-default` / `--accent: var(--accent-default)` pair is for
# the apps' runtime accent; each block already sets --accent itself, so the
# pair is dropped here.
#
# The generator runs with an empty, throwaway XDG_CONFIG_HOME, so it uses the
# design defaults (accent #eeb407) and never reads or writes a real ewe.conf.
#
# The type styles are emitted once, renamed .t-<style> (.t-body, .t-h1 …) so
# they cannot collide with the site's own class names.
#
#   npm run tokens [-- path/to/ewe/bin/ewe-theme]
set -euo pipefail
cd "$(dirname "$0")/.."
THEME=${1:-../ewe/bin/ewe-theme}
[ -f "$THEME" ] || { echo "xx no $THEME — pass the path to ewe/bin/ewe-theme" >&2; exit 1; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
export XDG_CONFIG_HOME="$tmp/config"
mkdir -p "$XDG_CONFIG_HOME"

build() { # scheme selector out
	local res
	res=$(python3 "$THEME" build --json /dev/null --css "$3" --scheme "$1" --selector "$2")
	case "$res" in *'"ok": true'*) ;; *) echo "xx ewe-theme build $1: $res" >&2; exit 1 ;; esac
}
build ewe-dark ':root, :root[data-theme="dark"]' "$tmp/dark.css"
build ewe-light ':root[data-theme="light"]' "$tmp/light.css"
build ewe-light ':root:not([data-theme="dark"])' "$tmp/system.css"
build ewe-dark '[data-scheme="ewe-dark"]' "$tmp/scoped.css"

[ -z "$(ls -A "$XDG_CONFIG_HOME")" ] || { echo "xx ewe-theme wrote into its config dir" >&2; exit 1; }

python3 - "$tmp" > src/tokens.css <<'PY'
import re, sys
tmp = sys.argv[1]

def parts(name):
    text = open(f"{tmp}/{name}.css").read()
    head = re.search(r"This file: scheme (\S+) \(([^)]*)\), accent (#[0-9a-f]{6})", text)
    m = re.search(r"^([^\n{/*][^\n{]*) \{\n(.*?)^\}\n", text, re.S | re.M)
    selector, body = m.group(1), m.group(2)
    # the apps' runtime-accent pair is not the site's (see the header)
    body = "\n".join(l for l in body.split("\n") if l.strip()
                     and not l.strip().startswith(("--accent-default:", "--accent: var(--accent-default)")))
    assert "--surface-base" in body and "--bg-1:" not in body, name
    types = text.split("/* type styles */", 1)[1].strip()
    version = re.search(r"design system, version (\d+)", text).group(1)
    return selector, body.rstrip("\n"), types, head, version

dark_sel, dark, types, dh, version = parts("dark")
light_sel, light, _, lh, _ = parts("light")
sys_sel, system, _, _, _ = parts("system")
scoped_sel, scoped, _, _, _ = parts("scoped")
# the scoped block needs only what a scheme changes: the colour roles, the
# shadows and the gradients (type, spacing and sizes are the same in both)
SCHEME_VARS = re.compile(r"^  --(ewellow|black|neutral|surface|scrim|glass|border-(subtle|strong)|text|accent|on-|focus-ring|success|warning|danger|info|shadow|gradient)")
scoped = "\n".join(l for l in scoped.split("\n") if SCHEME_VARS.match(l))

out = [
    "/* AUTO-GENERATED by scripts/sync-tokens.sh from `ewe-theme build`. Do not edit.",
    " *",
    f" * Ewe design system, version {version}. The generator (ewe/bin/ewe-theme) runs",
    " * with an empty config, so these are the design defaults:",
    f" *   dark   {dh.group(1)} ({dh.group(2)}), accent {dh.group(3)}",
    f" *   light  {lh.group(1)} ({lh.group(2)}), accent {lh.group(3)}",
    " *",
    " * Dark is the default. The light values apply when the visitor chose light",
    " * with the header toggle (data-theme=\"light\"), or when the system asks for",
    " * light and no choice was made. Refresh with `npm run tokens`.",
    " */",
    "",
    f"{dark_sel} {{", dark, "}", "",
    f"{light_sel} {{", light, "}", "",
    "@media (prefers-color-scheme: light) {",
    f"  {sys_sel} {{",
    "\n".join(("  " + l) if l else l for l in system.split("\n")),
    "  }",
    "}", "",
    "/* Ewe Dark colour roles for one part of a page, whatever the page wears */",
    f"{scoped_sel} {{", scoped, "}", "",
    "/* type styles (the generator's .body, .h1 … renamed .t-body, .t-h1 …) */",
    re.sub(r"^\.", ".t-", types, flags=re.M),
    "",
]
print("\n".join(out), end="")
PY
echo "ok src/tokens.css <- $THEME (ewe-dark, ewe-light)"
